### ISSUE TITLE
Nonstandard project structure

### ISSUE THREAD

**Issue by newhoggy** [hedgehogqa/haskell-hedgehog#56]
I'd like to be able to refresh the hedgehog git repository directly from `stack.yaml` like this, but it doesn't work for me because the `cabal` file isn't at the root directory.

```
packages:
- location:
    git: https://github.com/hedgehogqa/haskell-hedgehog
    commit: 24c9d0744806404558f3509123eb7b09d46aee0f
  extra-dep: true
```

**Comment by jystic** [comment]
This is a pretty common repository structure. [conduit](https://github.com/snoyberg/conduit), [http-client](https://github.com/snoyberg/http-client) and [amazonka](https://github.com/brendanhay/amazonka) all use this structure for example.

I don't use `stack` so I'm not sure if there's a way, but I'd be surprised if it couldn't load a source package from a sub-directory? `mafia`, `tinc` and `cabal` all support this.

**Comment by jystic** [comment]
After reading the [stack documentation](https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md#complex-package-locations-location), it seems as though you should be able to do this using the `subdirs` key:
```yaml
packages:
- location:
    git: https://github.com/hedgehogqa/haskell-hedgehog
    commit: 24c9d0744806404558f3509123eb7b09d46aee0f
  subdirs:
  - hedgehog
  extra-dep: true
```
